In [ ]:
import sqlite3
import pandas as pd

In [ ]:
# Conexion a base de datos
conexion = sqlite3.connect('sanoyfresco.db')

In [ ]:
# Cargar una tabla completa en un DataFrame
df = pd.read_sql_query('SELECT * FROM tickets', conexion)

#Mostar registros
df.head()

,id_pedido,id_cliente,fecha,hora,id_departamento,id_seccion,id_producto,nombre_producto,precio_unitario,cantidad,precio_total
0,1,112108,2023-02-02 00:00:00,10,4,83,49683,Pepino Kirby,0.99,4,3.96
1,1,112108,2023-02-02 00:00:00,10,4,24,13176,Bolsa de Bananas Orgánicas,2.45,4,9.80
2,1,112108,2023-02-02 00:00:00,10,4,24,47209,Aguacate Hass Orgánico,1.79,2,3.58
3,2,202279,2023-02-03 00:00:00,9,4,83,28985,Col Rizada Orgánica de Michigan,2.55,2,5.10
4,2,202279,2023-02-03 00:00:00,9,4,83,17794,Zanahorias,0.95,5,4.75

In [ ]:
# Cerrar la conexion a la base de datos
conexion.close()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4975718 entries, 0 to 4975717
Data columns (total 11 columns):
 #   Column           Dtype
---  ------           -----
 0   id_pedido        int64
 1   id_cliente       int64
 2   fecha            object
 3   hora             int64
 4   id_departamento  int64
 5   id_seccion       int64
 6   id_producto      int64
 7   nombre_producto  object
 8   precio_unitario  float64
 9   cantidad         int64
 10  precio_total     float64
dtypes: float64(2), int64(7), object(2)
memory usage: 417.6+ MB

In [ ]:
df.shape

(4975718, 11)

In [ ]:
df.describe()

,id_pedido,id_cliente,hora,id_departamento,id_seccion,id_producto,precio_unitario,cantidad,precio_total
count,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06,4.975718e+06
mean,1.710496e+06,1.028372e+05,1.341417e+01,4.992144e+00,5.809954e+01,2.862542e+04,1.596929e+00,5.015206e+00,8.009874e+00
std,9.873063e+05,5.950903e+04,4.259586e+00,3.382969e+00,3.909031e+01,1.292617e+04,6.695222e-01,1.983126e+00,4.803981e+00
min,1.000000e+00,1.000000e+00,0.000000e+00,4.000000e+00,1.600000e+01,4.605000e+03,6.200000e-01,1.000000e+00,6.200000e-01
25%,8.552620e+05,5.111900e+04,1.000000e+01,4.000000e+00,2.400000e+01,2.113700e+04,9.900000e-01,4.000000e+00,4.350000e+00
50%,1.710466e+06,1.024700e+05,1.300000e+01,4.000000e+00,2.400000e+01,2.620900e+04,1.490000e+00,5.000000e+00,7.140000e+00
75%,2.565128e+06,1.543180e+05,1.600000e+01,4.000000e+00,8.300000e+01,4.195000e+04,2.250000e+00,6.000000e+00,1.068000e+01
max,3.421083e+06,2.062090e+05,2.300000e+01,2.000000e+01,1.230000e+02,4.968300e+04,2.850000e+00,1.300000e+01,3.705000e+01

In [ ]:
df.isnull().sum()

id_pedido          0
id_cliente         0
fecha              0
hora               0
id_departamento    0
id_seccion         0
id_producto        0
nombre_producto    0
precio_unitario    0
cantidad           0
precio_total       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# eliminar duplicados, de momento no es necesario
# df.drop_duplicates(inplace=True)

In [ ]:
# cambio de tipo de dato
df['fecha'] = pd.to_datetime(df['fecha'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4975718 entries, 0 to 4975717
Data columns (total 11 columns):
 #   Column           Dtype
---  ------           -----
 0   id_pedido        int64
 1   id_cliente       int64
 2   fecha            datetime64[ns]
 3   hora             int64
 4   id_departamento  int64
 5   id_seccion       int64
 6   id_producto      int64
 7   nombre_producto  object
 8   precio_unitario  float64
 9   cantidad         int64
 10  precio_total     float64
dtypes: datetime64[ns](1), float64(2), int64(7), object(1)
memory usage: 417.6+ MB

In [ ]:
df_cesta = df[['id_pedido','nombre_producto']]
df_cesta

         id_pedido                  nombre_producto
0                1                     Pepino Kirby
1                1       Bolsa de Bananas Orgánicas
2                1           Aguacate Hass Orgánico
3                2  Col Rizada Orgánica de Michigan
4                2                       Zanahorias
...            ...                              ...
4975713    3421080            Leche Entera Orgánica
4975714    3421080      Racimo de Tomates Orgánicos
4975715    3421080                Cilantro Orgánico
4975716    3421082                           Fresas
4975717    3421083                           Banana

[4975718 rows x 2 columns]

In [ ]:
# Agrupar los productos por id_pedido
df_agrupado = df_cesta.groupby('id_pedido')['nombre_producto'].apply(lambda producto: ','.join(producto))
df_agrupado

id_pedido
1          Pepino Kirby,Bolsa de Bananas Orgánicas,Aguaca...
2                 Col Rizada Orgánica de Michigan,Zanahorias
3                                   Espinacas Baby Orgánicas
5          Bolsa de Bananas Orgánicas,Frambuesas Orgánica...
10         Banana,Cilantro Orgánico,Aguacate Orgánico,Ceb...
                                 ...
3421077    Frambuesas Orgánicas,Calabacín Orgánico,Leche ...
3421078                       Manzanas Gala Orgánicas,Banana
3421080    Leche Entera Orgánica,Racimo de Tomates Orgáni...
3421082                                               Fresas
3421083                                               Banana
Name: nombre_producto, Length: 2060188, dtype: object

In [ ]:
# Aplicar pd.get_dimuies() para transformar los productos en columnas con 0/1
df_transacciones = df_agrupado.str.get_dummies(sep=',')
df_transacciones

,Agua con Gas de Pomelo,Aguacate Hass Orgánico,Aguacate Orgánico,Ajo Orgánico,Apio Orgánico en Ramillete Pequeño,Arándanos Orgánicos,Banana,Bolsa de Bananas Orgánicas,Calabacín Orgánico,Cebolla Amarilla Orgánica,...,Manzana Honeycrisp Orgánica,Manzanas Gala Orgánicas,Pepino Kirby,Pepino Orgánico,Racimo de Tomates Orgánicos,Rúcula Baby Orgánica,Tomates Cherry Orgánicos,Uvas Rojas sin Semillas,Zanahorias,Zanahorias Baby Orgánicas
id_pedido,,,,,,,,,,,,,,,,,,,,,
1,0,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3421077,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3421078,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3421080,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3421082,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3421083,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#Soporte para cada producto
soporte = df_transacciones.mean() * 100
soporte.sort_values(ascending=False)

Banana                                23.809381
Bolsa de Bananas Orgánicas            19.129710
Fresas Orgánicas                      13.349170
Espinacas Baby Orgánicas              12.198935
Aguacate Hass Orgánico                10.703004
Aguacate Orgánico                      8.929331
Limón Grande                           7.791279
Fresas                                 7.241960
Limones                                7.107944
Leche Entera Orgánica                  6.918301
Frambuesas Orgánicas                   6.906797
Cebolla Amarilla Orgánica              5.706324
Ajo Orgánico                           5.521778
Calabacín Orgánico                     5.302429
Arándanos Orgánicos                    5.086138
Pepino Kirby                           4.840044
Manzana Fuji Orgánica                  4.502841
Limón Orgánico                         4.422266
Tomates Cherry Orgánicos               4.266795
Manzana Honeycrisp Orgánica            4.231216
Uvas Rojas sin Semillas                4.200733
Pepino Orgánico                        4.114091
Manzana Honeycrisp                     4.036476
Zanahorias Baby Orgánicas              3.898528
Agua con Gas de Pomelo                 3.839504
Crema Orgánica                         3.827855
Manzana Fuji Extra Grande Orgánica     3.780189
Cebollas Amarillas                     3.728592
Rúcula Baby Orgánica                   3.671849
Manzanas Gala Orgánicas                3.665442
Zanahorias                             3.647386
Coliflor Fresca                        3.597876
Hummus Original                        3.593798
Cilantro Orgánico                      3.538900
Crema                                  3.470606
Espárragos                             3.446724
Cebolla Roja Orgánica                  3.429687
Apio Orgánico en Ramillete Pequeño     3.427891
Col Rizada Orgánica de Michigan        3.396632
Racimo de Tomates Orgánicos            3.239267
dtype: float64

In [ ]:
# Funcion para calcular la confianza entre dos productos en la muestra
def confianza(antecedente, consecuente):
    # Casos donde se compraron ambos productos
    conjunto_ac = df_transacciones[
        (df_transacciones[antecedente] ==  1)
        &
        (df_transacciones[consecuente] == 1)
        ]
    # confianza = compras conjuntas / compras de producto A
    return len(conjunto_ac) / df_transacciones[antecedente].sum()

In [ ]:
# Funcion para calcular el lift entre dos productos en la muestra
def lift(antecedente, consecuente):
    soporte_a = df_transacciones[antecedente].mean()
    soporte_c = df_transacciones[consecuente].mean()
    conteo_ac = len(
        df_transacciones[
            (df_transacciones[antecedente] ==  1)
            &
            (df_transacciones[consecuente] == 1)
        ]
    )
    soporte_ac = conteo_ac /len(df_transacciones)
    return soporte_ac / (soporte_a * soporte_c)

In [ ]:
from itertools import combinations

#Definir un umbral para la confianza mínima
umbral_confianza = 0.05
asociaciones = []

#Generar combinaciones de productos y calcular confianza y lift
for antecedente, consecuente in combinations(df_transacciones.columns, 2):

    #Soporte del antecedente
    soporte_a = df_transacciones[antecedente].mean()

    #Calcular confianza
    conf = confianza(antecedente, consecuente)
    if conf > umbral_confianza:
        asociaciones.append({
            'antecedentes': antecedente,
            'consecuente': consecuente,
            'soporte_a': round(soporte_a * 100, 1),
            'confianza': round(conf * 100,1),
            'lift': round(lift(antecedente,consecuente),1)
        })

# Convertir las asociaciones en un DataFrame
df_asociaciones = pd.DataFrame(asociaciones)

# Ordenar las asociaciones por confianza de mayor a menor
df_asociaciones.sort_values(by='lift', ascending= False, inplace= True)

df_asociaciones

,antecedentes,consecuente,soporte_a,confianza,lift
185,Cebolla Roja Orgánica,Cilantro Orgánico,3.4,12.8,3.6
224,Cilantro Orgánico,Limones,3.5,25.4,3.6
61,Ajo Orgánico,Cebolla Amarilla Orgánica,5.5,20.1,3.5
106,Apio Orgánico en Ramillete Pequeño,Zanahorias,3.4,12.0,3.3
102,Apio Orgánico en Ramillete Pequeño,Pepino Orgánico,3.4,12.7,3.1
...,...,...,...,...,...
136,Bolsa de Bananas Orgánicas,Limón Grande,19.1,5.2,0.7
38,Aguacate Orgánico,Bolsa de Bananas Orgánicas,8.9,13.0,0.7
58,Ajo Orgánico,Banana,5.5,17.4,0.7
3,Agua con Gas de Pomelo,Bolsa de Bananas Orgánicas,3.8,13.2,0.7
15,Aguacate Hass Orgánico,Banana,10.7,14.6,0.6

In [ ]:
# Crear una tabla con los productos únicos y las columnas correspondientes
productos_unicos = df[['id_producto','id_seccion','id_departamento','nombre_producto']].drop_duplicates()

productos_unicos

,id_producto,id_seccion,id_departamento,nombre_producto
0,49683,83,4,Pepino Kirby
1,13176,24,4,Bolsa de Bananas Orgánicas
2,47209,24,4,Aguacate Hass Orgánico
3,28985,83,4,Col Rizada Orgánica de Michigan
4,17794,83,4,Zanahorias
5,21903,123,4,Espinacas Baby Orgánicas
7,27966,123,4,Frambuesas Orgánicas
9,24852,24,4,Banana
10,31717,16,4,Cilantro Orgánico
11,47766,24,4,Aguacate Orgánico
12,4605,83,4,Cebollas Amarillas
13,21137,24,4,Fresas Orgánicas
14,49235,53,16,Crema Orgánica
15,27845,84,16,Leche Entera Orgánica
16,45066,24,4,Manzana Honeycrisp
17,44632,115,7,Agua con Gas de Pomelo
19,46979,83,4,Espárragos
21,42265,123,4,Zanahorias Baby Orgánicas
26,8518,83,4,Cebolla Roja Orgánica
34,41950,83,4,Racimo de Tomates Orgánicos
35,47626,24,4,Limón Grande
38,22935,83,4,Cebolla Amarilla Orgánica
41,4920,123,4,Uvas Rojas sin Semillas
47,21616,123,4,Rúcula Baby Orgánica
49,28204,24,4,Manzana Fuji Orgánica
52,16797,24,4,Fresas
53,39275,123,4,Arándanos Orgánicos
57,37646,24,4,Manzanas Gala Orgánicas
59,40706,123,4,Tomates Cherry Orgánicos
60,5876,24,4,Limón Orgánico
67,30391,83,4,Pepino Orgánico
70,24964,83,4,Ajo Orgánico
75,19057,24,4,Manzana Fuji Extra Grande Orgánica
85,26209,24,4,Limones
99,8277,24,4,Manzana Honeycrisp Orgánica
138,27104,83,4,Coliflor Fresca
156,30489,67,20,Hummus Original
159,44359,83,4,Apio Orgánico en Ramillete Pequeño
172,45007,83,4,Calabacín Orgánico
289,27086,53,16,Crema

In [ ]:
df_asociaciones_enriquecido = df_asociaciones.merge(productos_unicos, left_on='antecedentes', right_on='nombre_producto', how='left').drop(columns=['nombre_producto'])
df_asociaciones_enriquecido.columns = ['antecedentes', 'consecuente', 'soporte_a', 'confianza', 'lift', 'id_producto_a', 'id_seccion_a', 'id_departamento_a']
df_asociaciones_enriquecido

,antecedentes,consecuente,soporte_a,confianza,lift,id_producto_a,id_seccion_a,id_departamento_a
0,Cebolla Roja Orgánica,Cilantro Orgánico,3.4,12.8,3.6,8518,83,4
1,Cilantro Orgánico,Limones,3.5,25.4,3.6,31717,16,4
2,Ajo Orgánico,Cebolla Amarilla Orgánica,5.5,20.1,3.5,24964,83,4
3,Apio Orgánico en Ramillete Pequeño,Zanahorias,3.4,12.0,3.3,44359,83,4
4,Apio Orgánico en Ramillete Pequeño,Pepino Orgánico,3.4,12.7,3.1,44359,83,4
...,...,...,...,...,...,...,...,...
394,Bolsa de Bananas Orgánicas,Limón Grande,19.1,5.2,0.7,13176,24,4
395,Aguacate Orgánico,Bolsa de Bananas Orgánicas,8.9,13.0,0.7,47766,24,4
396,Ajo Orgánico,Banana,5.5,17.4,0.7,24964,83,4
397,Agua con Gas de Pomelo,Bolsa de Bananas Orgánicas,3.8,13.2,0.7,44632,115,7
398,Aguacate Hass Orgánico,Banana,10.7,14.6,0.6,47209,24,4

In [ ]:
df_asociaciones_enriquecido.to_csv('reglas.csv', index=False, sep=';', decimal=',')

In [ ]:
df_asociaciones_enriquecido.to_csv('reglas.csv', index=False)